version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    # Default linters
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    # Formatting
    - misspell
    # Code quality
    - revive
    # Security-adjacent
    - bodyclose
    - noctx
    - sqlclosecheck
  settings:
    revive:
      rules:
        - name: exported
          severity: warning
        - name: var-naming
          severity: warning
        - name: unexported-return
          severity: warning
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US
  exclusions:
    presets:
      - comments
      - std-error-handling

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
