run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    # Default linters
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    # Formatting
    - gofmt
    - misspell
    # Code quality
    - revive
    # Security-adjacent
    - bodyclose
    - noctx
    - sqlclosecheck

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: unexported-return
        severity: warning
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
